/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tictactoe;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author danie
 */
public class Inicio extends javax.swing.JFrame {
    private int turn = 0;
    private  ImageIcon circulonegro = new ImageIcon("C:\\Users\\danie\\Desktop\\Repositorios 25-26\\DESINDAM2\\TicTacToe\\src\\main\\java\\com\\mycompany\\tictactoe\\images\\images.jpg");
    private  ImageIcon cruzroja = new ImageIcon("C:\\Users\\danie\\Desktop\\Repositorios 25-26\\DESINDAM2\\TicTacToe\\src\\main\\java\\com\\mycompany\\tictactoe\\images\\cruz_roja.jpg");
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());
    private JButton[] botones = new JButton[9];
    Logica  l = new Logica(botones ,circulonegro,cruzroja);;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
       
        
        botones[0] = jButton1;
        botones[1] = jButton2;
        botones[2] = jButton3;
        botones[3] = jButton4;
        botones[4] = jButton5;
        botones[5] = jButton6;
        botones[6] = jButton7;
        botones[7] = jButton8;
        botones[8] = jButton9;
      
        for(JButton b : botones){
            b.addActionListener((e) -> {
                changeImg(e, l);
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        getContentPane().setLayout(new java.awt.GridLayout(4, 3, 1, 1));
        getContentPane().add(jButton1);
        getContentPane().add(jButton2);
        getContentPane().add(jButton3);
        getContentPane().add(jButton4);
        getContentPane().add(jButton5);
        getContentPane().add(jButton6);
        getContentPane().add(jButton7);
        getContentPane().add(jButton8);
        getContentPane().add(jButton9);

        jButton10.setText("RESET");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        l.reset();
    }//GEN-LAST:event_jButton10ActionPerformed
    private void changeImg(java.awt.event.ActionEvent evt , Logica l) {
             // TODO add your handling code here:
        turn++;
        if (turn > 2) {
            turn = 1;
        }
        
        int x[][] = l.getX();
        for(int [] r : x) {
            for(int m : r) {
                System.out.print(m + "");
            }
            System.out.println();
                    
        }
        
        JButton n = (JButton) evt.getSource();
        System.out.println("Botón pulsado");

        switch (turn) {
            case 1:
                n.setIcon(circulonegro);
                
                break;
            case 2:
                n.setIcon(cruzroja);
                break;
            default:
                break;
        }

        // Desactivar el botón después de usarlo
        n.setEnabled(false);
        int m = l.actualizarDatos();
        if(m == 1) {
            for(JButton b : botones) {
                b.setEnabled(false);
            }
        }else if(m == 2) {
            for(JButton b : botones) {
                b.setEnabled(false);
            }
        }else {
            System.out.println(m);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
