/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoimagen;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author danie
 */
public class Inicio extends javax.swing.JFrame {
    private int i = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Desktop\\Repositorios 25-26\\DESINDAM2\\ProyectoImagen\\src\\main\\java\\com\\mycompany\\proyectoimagen\\images\\Maxwell Cat Sticker – Maxwell Cat Spinning – discover and share GIFs.gif")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(96, 96));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Desktop\\Repositorios 25-26\\DESINDAM2\\ProyectoImagen\\src\\main\\java\\com\\mycompany\\proyectoimagen\\images\\rigby-cat-stare.gif")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       i++;
       
       if(i > 3) {
           i = 1;
       }
        switch (i) {
            case 1:
                jLabel1.setIcon(new ImageIcon("C:\\Users\\danie\\Desktop\\Repositorios 25-26\\DESINDAM2\\ProyectoImagen\\src\\main\\java\\com\\mycompany\\proyectoimagen\\images\\rigby-cat-stare.gif"));
                jButton1.setIcon(new ImageIcon("C:\\Users\\danie\\Desktop\\Repositorios 25-26\\DESINDAM2\\ProyectoImagen\\src\\main\\java\\com\\mycompany\\proyectoimagen\\images\\fatfatmillycat-silly-cat.gif"));
                break;
            case 2:
                jLabel1.setIcon(new ImageIcon("C:\\Users\\danie\\Desktop\\Repositorios 25-26\\DESINDAM2\\ProyectoImagen\\src\\main\\java\\com\\mycompany\\proyectoimagen\\images\\Maxwell Cat Sticker – Maxwell Cat Spinning – discover and share GIFs.gif"));
                jButton1.setIcon(new ImageIcon("C:\\Users\\danie\\Desktop\\Repositorios 25-26\\DESINDAM2\\ProyectoImagen\\src\\main\\java\\com\\mycompany\\proyectoimagen\\images\\rigby-cat-stare.gif"));
                break;
            case 3:
                jLabel1.setIcon(new ImageIcon("C:\\Users\\danie\\Desktop\\Repositorios 25-26\\DESINDAM2\\ProyectoImagen\\src\\main\\java\\com\\mycompany\\proyectoimagen\\images\\fatfatmillycat-silly-cat.gif"));
                jButton1.setIcon(new ImageIcon("C:\\Users\\danie\\Desktop\\Repositorios 25-26\\DESINDAM2\\ProyectoImagen\\src\\main\\java\\com\\mycompany\\proyectoimagen\\images\\rigby-cat-stare.gif"));
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
